from theseus.base.callbacks import CALLBACKS_REGISTRY

from .gradcam_callback import GradCAMVisualizationCallback
from .visualize_callback import ClassificationVisualizerCallback

CALLBACKS_REGISTRY.register(ClassificationVisualizerCallback)
CALLBACKS_REGISTRY.register(GradCAMVisualizationCallback)
