from .visualize_callbacks import ClassificationVisualizerCallbacks
from .gradcam_callbacks import GradCAMVisualizationCallbacks 
from theseus.cv.base.callbacks import CALLBACKS_REGISTRY

CALLBACKS_REGISTRY.register(ClassificationVisualizerCallbacks)
CALLBACKS_REGISTRY.register(GradCAMVisualizationCallbacks)