from theseus.base.callbacks import CALLBACKS_REGISTRY

from .gradcam_callbacks import GradCAMVisualizationCallbacks
from .visualize_callbacks import ClassificationVisualizerCallbacks

CALLBACKS_REGISTRY.register(ClassificationVisualizerCallbacks)
CALLBACKS_REGISTRY.register(GradCAMVisualizationCallbacks)
