global:
  exp_name: null
  exist_ok: false
  debug: true
  cfg_transform: configs/classification/transform.yaml
  save_dir: /content/main/runs
  device: cuda:0
  pretrained: null
  resume: null
trainer:
  name: SupervisedTrainer
  args:
    num_iterations: 10000
    clip_grad: 10.0
    evaluate_interval: 1
    print_interval: 20
    save_interval: 1000
    use_fp16: true
callbacks:
  - name: LoggerCallbacks
    args: null
  - name: CheckpointCallbacks
    args:
      best_key: bl_acc
  - name: VisualizerCallbacks
    args: null
  - name: TensorboardCallbacks
    args: null
model:
  name: BaseTimmModel
  args:
    name: convnext_small
    from_pretrained: true
    num_classes: 2
loss:
  name: CELoss
metrics:
  - name: Accuracy
    args: null
  - name: BalancedAccuracyMetric
    args: null
  - name: F1ScoreMetric
    args:
      average: weighted
  - name: ConfusionMatrix
    args: null
  - name: ErrorCases
    args:
optimizer:
  name: AdamW
  args:
    lr: 0.001
    weight_decay: 0.0005
    betas:
      - 0.937
      - 0.999
scheduler:
  name: SchedulerWrapper
  args:
    scheduler_name: cosine2
    t_initial: 7
    t_mul: 0.9
    eta_mul: 0.9
    eta_min: 1.0e-06
data:
  dataset:
    train:
      name: ImageFolderDataset
      args:
        image_dir: /content/main/data/dog-vs-cats/train
        txt_classnames: configs/classification/classes.txt
    val:
      name: ImageFolderDataset
      args:
        image_dir: /content/main/data/dog-vs-cats/val
        txt_classnames: configs/classification/classes.txt
  dataloader:
    train:
      name: DataLoaderWithCollator
      args:
        batch_size: 32
        drop_last: true
        shuffle: false
        collate_fn:
          name: MixupCutmixCollator
          args:
            mixup_alpha: 0.4
            cutmix_alpha: 1.0
            weight: [0.2, 0.2]
        sampler:
          name: BalanceSampler
          args:
    val:
      name: DataLoaderWithCollator
      args:
        batch_size: 32
        drop_last: false
        shuffle: true
