from theseus.classification.callbacks.visualize_callbacks import ClassificationVisualizerCallbacks
from theseus.base.callbacks import CALLBACKS_REGISTRY

CALLBACKS_REGISTRY.register(ClassificationVisualizerCallbacks)